### ISSUE TITLE
How to use ip_range for ip4 and ip6 data on the new maxmind city tables

### ISSUE THREAD

**Issue by ghaleon16** [RhodiumToad/ip4r#1]
The new maxmind tables only have a starting ip and no ending ip. and are in ip4 and ip6 format 

for example.  2001:8a0:ebc0::/49     

so ip4r( beginip, endip) doesn't work to make a new ip_range column as there is not a beginning and ending ip it is all in one column now. How would we create a new ip_range colum from this data????

How would we run a speed test on such a column using ip4r ?   

How would we change this ? ---> EXPLAIN ANALYZE SELECT \* FROM locations WHERE locations.id = ( select geoname_id from blocks where (network_start_ip::ipaddress / network_prefi
[23:37:51]  <WolfGoethe>    x_length) >>= '::ffff:65.200.93.73' );

**Comment by RhodiumToad** [comment]
non-bug
