### ISSUE TITLE
Build error against PostgreSQL 11

### ISSUE THREAD

**Issue by devrimgunduz** [RhodiumToad/ip4r#10]
Hi,

PostgreSQL 11 beta1 is out today, and I'm getting the following errors:
 
`
/usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o ip6r.bc ip6r.c
In file included from ipaddr.c:5:
ip4r_funcs.h: In function 'ip4r_from_cidr':
ip4r_funcs.h:74:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip4r_funcs.h:74:16: note: each undeclared identifier is reported only once for each function it appears in
ip4r_funcs.h:79:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
ip4r_funcs.h: In function 'ip4r_from_inet':
ip4r_funcs.h:87:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip4r_funcs.h:90:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
In file included from ipaddr.c:6:
ip6r_funcs.h: In function 'ip6_valid_netmask':
ip6r_funcs.h:109:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip6r_funcs.h:120:16: error: 'TRUE' undeclared (first use in this function)
         return TRUE;
                ^~~~
ip6r_funcs.h: In function 'ip6r_from_cidr':
ip6r_funcs.h:183:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip6r_funcs.h:189:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
ip6r_funcs.h: In function 'ip6r_from_inet':
ip6r_funcs.h:198:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip6r_funcs.h:203:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
make[1]: *** [<builtin>: ipaddr.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ip4r.c:5:
ip4r_funcs.h: In function 'ip4r_from_cidr':
ip4r_funcs.h:74:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip4r_funcs.h:74:16: note: each undeclared identifier is reported only once for each function it appears in
ip4r_funcs.h:79:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
ip4r_funcs.h: In function 'ip4r_from_inet':
ip4r_funcs.h:87:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip4r_funcs.h:90:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
ip4r.c: In function 'ip4r_from_str':
ip4r.c:22:24: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
                 return FALSE;
                        ^~~~~
                        FILE
ip4r.c:25:20: error: 'TRUE' undeclared (first use in this function)
             return TRUE;
                    ^~~~
In file included from ipr.h:4,
                 from ip4r.c:3:
ip4r.c: In function 'ip4r_contains':
ip4r.c:922:44: error: 'TRUE' undeclared (first use in this function)
                                            TRUE) );
                                            ^~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
ip4r.c:920:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( ip4r_contains_internal(PG_GETARG_IP4R_P(0),
     ^~~~~~~~~~~~~~
ip4r.c: In function 'ip4r_contains_strict':
ip4r.c:931:44: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
                                            FALSE) );
                                            ^~~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
ip4r.c:929:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( ip4r_contains_internal(PG_GETARG_IP4R_P(0),
     ^~~~~~~~~~~~~~
ip4r.c: In function 'ip4r_contained_by':
ip4r.c:940:44: error: 'TRUE' undeclared (first use in this function)
                                            TRUE) );
                                            ^~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
ip4r.c:938:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( ip4r_contains_internal(PG_GETARG_IP4R_P(1),
     ^~~~~~~~~~~~~~
ip4r.c: In function 'ip4r_contained_by_strict':
ip4r.c:949:44: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
                                            FALSE) );
                                            ^~~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
ip4r.c:947:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( ip4r_contains_internal(PG_GETARG_IP4R_P(1),
     ^~~~~~~~~~~~~~
ip4r.c: In function 'gip4r_leaf_consistent':
ip4r.c:1418:55: error: 'TRUE' undeclared (first use in this function)
             return ip4r_contains_internal(key, query, TRUE);
                                                       ^~~~
ip4r.c:1422:55: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
             return ip4r_contains_internal(key, query, FALSE);
                                                       ^~~~~
                                                       FILE
ip4r.c: In function 'gip4r_internal_consistent':
ip4r.c:1462:55: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
             return ip4r_contains_internal(key, query, FALSE);
                                                       ^~~~~
                                                       FILE
ip4r.c:1465:55: error: 'TRUE' undeclared (first use in this function)
             return ip4r_contains_internal(key, query, TRUE);
                                                       ^~~~
ip4r.c: In function 'ip4r_from_str':
ip4r.c:73:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
In file included from ip4r.c:5:
ip4r_funcs.h: In function 'ip4r_from_cidr':
ip4r_funcs.h:80:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip4r_funcs.h: In function 'ip4r_from_inet':
ip4r_funcs.h:91:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip4r.c: In function 'ip4r_contains':
ip4r.c:923:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip4r.c: In function 'ip4r_contains_strict':
ip4r.c:932:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip4r.c: In function 'ip4r_contained_by':
ip4r.c:941:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip4r.c: In function 'ip4r_contained_by_strict':
ip4r.c:950:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip4r.c: In function 'gip4r_leaf_consistent':
ip4r.c:1432:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip4r.c: In function 'gip4r_internal_consistent':
ip4r.c:1469:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [<builtin>: ip4r.o] Error 1
In file included from ip6r.c:5:
ip6r_funcs.h: In function 'ip6_valid_netmask':
ip6r_funcs.h:109:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip6r_funcs.h:109:16: note: each undeclared identifier is reported only once for each function it appears in
ip6r_funcs.h:120:16: error: 'TRUE' undeclared (first use in this function)
         return TRUE;
                ^~~~
ip6r_funcs.h: In function 'ip6r_from_cidr':
ip6r_funcs.h:183:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip6r_funcs.h:189:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
ip6r_funcs.h: In function 'ip6r_from_inet':
ip6r_funcs.h:198:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip6r_funcs.h:203:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
ip6r.c: In function 'ip6r_from_str':
ip6r.c:22:24: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
                 return FALSE;
                        ^~~~~
                        FILE
ip6r.c:25:20: error: 'TRUE' undeclared (first use in this function)
             return TRUE;
                    ^~~~
In file included from ipr.h:4,
                 from ip6r.c:3:
ip6r.c: In function 'ip6r_contains':
ip6r.c:1071:44: error: 'TRUE' undeclared (first use in this function)
                                            TRUE) );
                                            ^~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
ip6r.c:1069:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( ip6r_contains_internal(PG_GETARG_IP6R_P(0),
     ^~~~~~~~~~~~~~
ip6r.c: In function 'ip6r_contains_strict':
ip6r.c:1080:44: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
                                            FALSE) );
                                            ^~~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
ip6r.c:1078:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( ip6r_contains_internal(PG_GETARG_IP6R_P(0),
     ^~~~~~~~~~~~~~
ip6r.c: In function 'ip6r_contained_by':
ip6r.c:1089:44: error: 'TRUE' undeclared (first use in this function)
                                            TRUE) );
                                            ^~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
ip6r.c:1087:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( ip6r_contains_internal(PG_GETARG_IP6R_P(1),
     ^~~~~~~~~~~~~~
ip6r.c: In function 'ip6r_contained_by_strict':
ip6r.c:1098:44: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
                                            FALSE) );
                                            ^~~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
ip6r.c:1096:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( ip6r_contains_internal(PG_GETARG_IP6R_P(1),
     ^~~~~~~~~~~~~~
ip6r.c: In function 'gip6r_leaf_consistent':
ip6r.c:1583:55: error: 'TRUE' undeclared (first use in this function)
             return ip6r_contains_internal(key, query, TRUE);
                                                       ^~~~
ip6r.c:1587:55: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
             return ip6r_contains_internal(key, query, FALSE);
                                                       ^~~~~
                                                       FILE
ip6r.c: In function 'gip6r_internal_consistent':
ip6r.c:1627:55: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
             return ip6r_contains_internal(key, query, FALSE);
                                                       ^~~~~
                                                       FILE
ip6r.c:1630:55: error: 'TRUE' undeclared (first use in this function)
             return ip6r_contains_internal(key, query, TRUE);
                                                       ^~~~
ip6r.c: In function 'ip6r_from_str':
ip6r.c:73:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
In file included from ip6r.c:5:
ip6r_funcs.h: In function 'ip6r_from_cidr':
ip6r_funcs.h:190:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip6r_funcs.h: In function 'ip6r_from_inet':
ip6r_funcs.h:204:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip6r.c: In function 'ip6r_contains':
ip6r.c:1072:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip6r.c: In function 'ip6r_contains_strict':
ip6r.c:1081:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip6r.c: In function 'ip6r_contained_by':
ip6r.c:1090:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip6r.c: In function 'ip6r_contained_by_strict':
ip6r.c:1099:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip6r.c: In function 'gip6r_leaf_consistent':
ip6r.c:1597:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ip6r.c: In function 'gip6r_internal_consistent':
ip6r.c:1634:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
In file included from iprange.c:5:
ip4r_funcs.h: In function 'ip4r_from_cidr':
ip4r_funcs.h:74:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip4r_funcs.h:74:16: note: each undeclared identifier is reported only once for each function it appears in
ip4r_funcs.h:79:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
ip4r_funcs.h: In function 'ip4r_from_inet':
ip4r_funcs.h:87:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip4r_funcs.h:90:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
In file included from iprange.c:6:
ip6r_funcs.h: In function 'ip6_valid_netmask':
ip6r_funcs.h:109:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip6r_funcs.h:120:16: error: 'TRUE' undeclared (first use in this function)
         return TRUE;
                ^~~~
ip6r_funcs.h: In function 'ip6r_from_cidr':
ip6r_funcs.h:183:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip6r_funcs.h:189:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
ip6r_funcs.h: In function 'ip6r_from_inet':
ip6r_funcs.h:198:16: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
         return FALSE;
                ^~~~~
                FILE
ip6r_funcs.h:203:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^~~~
In file included from ipr.h:4,
                 from iprange.c:3:
iprange.c: In function 'iprange_contains':
iprange.c:1205:13: error: 'TRUE' undeclared (first use in this function)
             TRUE) );
             ^~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
iprange.c:1203:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( iprange_contains_internal(PG_GETARG_DATUM(0),
     ^~~~~~~~~~~~~~
iprange.c: In function 'iprange_contains_strict':
iprange.c:1214:13: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
             FALSE) );
             ^~~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
iprange.c:1212:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( iprange_contains_internal(PG_GETARG_DATUM(0),
     ^~~~~~~~~~~~~~
iprange.c: In function 'iprange_contained_by':
iprange.c:1223:13: error: 'TRUE' undeclared (first use in this function)
             TRUE) );
             ^~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
iprange.c:1221:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( iprange_contains_internal(PG_GETARG_DATUM(1),
     ^~~~~~~~~~~~~~
iprange.c: In function 'iprange_contained_by_strict':
iprange.c:1232:13: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
             FALSE) );
             ^~~~~
/usr/pgsql-11/include/server/postgres.h:387:36: note: in definition of macro 'BoolGetDatum'
 #define BoolGetDatum(X) ((Datum) ((X) ? 1 : 0))
                                    ^
iprange.c:1230:5: note: in expansion of macro 'PG_RETURN_BOOL'
     PG_RETURN_BOOL( iprange_contains_internal(PG_GETARG_DATUM(1),
     ^~~~~~~~~~~~~~
In file included from ipr.h:6,
                 from iprange.c:3:
iprange.c: In function 'gipr_compress':
iprange.c:1513:23: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
        entry->offset, FALSE);
                       ^~~~~
/usr/pgsql-11/include/server/access/gist.h:171:37: note: in definition of macro 'gistentryinit'
    (e).offset = (o); (e).leafkey = (l); } while (0)
                                     ^
iprange.c: In function 'gipr_decompress':
iprange.c:1532:22: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
       entry->offset, FALSE);
                      ^~~~~
/usr/pgsql-11/include/server/access/gist.h:171:37: note: in definition of macro 'gistentryinit'
    (e).offset = (o); (e).leafkey = (l); } while (0)
                                     ^
iprange.c: In function 'gipr_leaf_consistent':
iprange.c:2148:64: error: 'TRUE' undeclared (first use in this function)
     return ip4r_contains_internal(&key->ipr.ip4r, &query.ip4r, TRUE);
                                                                ^~~~
iprange.c:2152:64: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
     return ip4r_contains_internal(&key->ipr.ip4r, &query.ip4r, FALSE);
                                                                ^~~~~
                                                                FILE
iprange.c: In function 'gipr_internal_consistent':
iprange.c:2221:64: error: 'FALSE' undeclared (first use in this function); did you mean 'FILE'?
     return ip4r_contains_internal(&key->ipr.ip4r, &query.ip4r, FALSE);
                                                                ^~~~~
                                                                FILE
iprange.c:2224:64: error: 'TRUE' undeclared (first use in this function)
     return ip4r_contains_internal(&key->ipr.ip4r, &query.ip4r, TRUE);
                                                                ^~~~
In file included from iprange.c:5:
ip4r_funcs.h: In function 'ip4r_from_cidr':
ip4r_funcs.h:80:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
In file included from iprange.c:6:
ip6r_funcs.h: In function 'ip6r_from_cidr':
ip6r_funcs.h:190:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
In file included from iprange.c:5:
ip4r_funcs.h: In function 'ip4r_from_inet':
ip4r_funcs.h:91:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
In file included from iprange.c:6:
ip6r_funcs.h: In function 'ip6r_from_inet':
ip6r_funcs.h:204:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
iprange.c: In function 'iprange_contains':
iprange.c:1206:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
iprange.c: In function 'iprange_contains_strict':
iprange.c:1215:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
iprange.c: In function 'iprange_contained_by':
iprange.c:1224:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
iprange.c: In function 'iprange_contained_by_strict':
iprange.c:1233:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
iprange.c: In function 'gipr_leaf_consistent':
iprange.c:2180:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
iprange.c: In function 'gipr_internal_consistent':
iprange.c:2243:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [<builtin>: ip6r.o] Error 1
make[1]: *** [<builtin>: iprange.o] Error 1
In file included from ip4r.c:5:
./ip4r_funcs.h:74:16: error: use of undeclared identifier 'FALSE'
        return FALSE;
               ^
./ip4r_funcs.h:76:16: error: use of undeclared identifier 'FALSE'
        return FALSE;
               ^
./ip4r_funcs.h:79:12: error: use of undeclared identifier 'TRUE'
    return TRUE;
           ^
./ip4r_funcs.h:87:16: error: use of undeclared identifier 'FALSE'
        return FALSE;
               ^
./ip4r_funcs.h:90:12: error: use of undeclared identifier 'TRUE'
    return TRUE;
           ^
ip4r.c:22:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip4r.c:25:20: error: use of undeclared identifier 'TRUE'
            return TRUE;
                   ^
ip4r.c:33:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip4r.c:37:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip4r.c:40:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip4r.c:48:20: error: use of undeclared identifier 'TRUE'
            return TRUE;
                   ^
ip4r.c:58:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip4r.c:62:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip4r.c:64:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip4r.c:66:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip4r.c:71:20: error: use of undeclared identifier 'FALSE'
            return FALSE;      /* can't happen */
                   ^
ip4r.c:922:44: error: use of undeclared identifier 'TRUE'
                                           TRUE) );
                                           ^
ip4r.c:931:44: error: use of undeclared identifier 'FALSE'
                                           FALSE) );
                                           ^
ip4r.c:940:44: error: use of undeclared identifier 'TRUE'
                                           TRUE) );
                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [/usr/pgsql-11/lib/pgxs/src/makefiles/../../src/Makefile.global:1009: ip4r.bc] Error 1
In file included from ip6r.c:5:
./ip6r_funcs.h:109:16: error: use of undeclared identifier 'FALSE'
        return FALSE;
               ^
./ip6r_funcs.h:120:16: error: use of undeclared identifier 'TRUE'
        return TRUE;
               ^
./ip6r_funcs.h:183:16: error: use of undeclared identifier 'FALSE'
        return FALSE;
               ^
./ip6r_funcs.h:185:16: error: use of undeclared identifier 'FALSE'
        return FALSE;
               ^
./ip6r_funcs.h:189:12: error: use of undeclared identifier 'TRUE'
    return TRUE;
           ^
./ip6r_funcs.h:198:16: error: use of undeclared identifier 'FALSE'
        return FALSE;
               ^
./ip6r_funcs.h:203:12: error: use of undeclared identifier 'TRUE'
    return TRUE;
           ^
ip6r.c:22:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip6r.c:25:20: error: use of undeclared identifier 'TRUE'
            return TRUE;
                   ^
ip6r.c:33:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip6r.c:37:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip6r.c:40:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip6r.c:48:20: error: use of undeclared identifier 'TRUE'
            return TRUE;
                   ^
ip6r.c:58:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip6r.c:62:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip6r.c:64:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip6r.c:66:24: error: use of undeclared identifier 'FALSE'
                return FALSE;
                       ^
ip6r.c:71:20: error: use of undeclared identifier 'FALSE'
            return FALSE;      /* can't happen */
                   ^
ip6r.c:1071:44: error: use of undeclared identifier 'TRUE'
                                           TRUE) );
                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [/usr/pgsql-11/lib/pgxs/src/makefiles/../../src/Makefile.global:1009: ip6r.bc] Error 1

`

Regards, Devrim

**Comment by devrimgunduz** [comment]
BTW, this is against GCC 8.1.1 on Fedora 28.

**Comment by RhodiumToad** [comment]
I actually fixed this in the code already (see master branch), but didn't tag a new release yet (I should have done that before beta1 came out but forgot). I'll tag it shortly.

**Comment by devrimgunduz** [comment]
Thanks!
