### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by joanix** [RhodiumToad/ip4r#11]
Last commit is talking about "Update README for 2.3", but the rest of the files seem to be concerned only about version 2.2; which raises several questions:

Is this actually a work-in-progress (meaning files for 2.3, i.e.: all the .SQL files are still missing)?
The change in the README (fix long-standing bug in binary-mode I/O of iprange type) has actually been made?
Is ip4r actually "PostgreSQL 11" ready?

Regards

**Comment by RhodiumToad** [comment]
2.3 is released (see releases page), but since there were no SQL-level changes the SQL files still say 2.2. (I should really have numbered it 2.2.1, that was an oversight at the time that I didn't notice until after pushing the tag.)

Last I checked it works fine on pg11.
