### ISSUE TITLE
trying to make but failing on mac os big sir 11.2

### ISSUE THREAD

**Issue by arosenk35** [RhodiumToad/ip4r#20]
i have installed Xcode but i still get ... error .... /usr/local/include/postgresql/server/c.h:59:10: fatal error: 'stdio.h' file not
      found
#include <stdio.h>
         ^~~~~~~~~

any guidance is appreciated

**Comment by RhodiumToad** [comment]
This usually means some mismatch between the macos version / xcode version (I don't know which) used to build the postgresql server, and the one that you have installed. The build will not succeed if they don't match, and I don't have the ability to assist you in that case.
