### ISSUE TITLE
pg_dump errors

### ISSUE THREAD

**Issue by plockaby** [RhodiumToad/ip4r#8]
Hello, I found this new maintenance location of ip4r after pg_foundry gave up the ghost. I installed the latest version of ip4r here when upgrading to postgres 9.5.6. Now I get this error when doing pg_dump:

```pg_dump: could not parse numeric array "2281": too many numbers```

Other people have reported the same error on the mailing list when using ip4r: 

[http://postgresql.nabble.com/Error-dumping-9-4-could-not-parse-numeric-array-td5937116.html](http://postgresql.nabble.com/Error-dumping-9-4-could-not-parse-numeric-array-td5937116.html)

This error is problematic since I can no longer run pg_dump.

**Comment by RhodiumToad** [comment]
Sorry for the delay. 2.2 fixes this.
